from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.units import cm
from datetime import datetime

def generate_pdf(articles: list, output_path: str = "ai_digest.pdf"):
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                             leftMargin=2*cm, rightMargin=2*cm,
                             topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    story = []

    # Custom styles
    title_style = ParagraphStyle("DigestTitle", parent=styles["Title"],
                                  fontSize=22, textColor=colors.HexColor("#1a1a2e"),
                                  spaceAfter=6)
    date_style  = ParagraphStyle("DateLine", parent=styles["Normal"],
                                  fontSize=10, textColor=colors.grey, spaceAfter=20)
    num_style   = ParagraphStyle("NewsNum", parent=styles["Heading2"],
                                  fontSize=13, textColor=colors.HexColor("#0f3460"))
    src_style   = ParagraphStyle("Source", parent=styles["Normal"],
                                  fontSize=9, textColor=colors.HexColor("#e94560"),
                                  spaceAfter=4)
    body_style  = ParagraphStyle("Body", parent=styles["Normal"],
                                  fontSize=10, leading=14, spaceAfter=6)
    url_style   = ParagraphStyle("URL", parent=styles["Normal"],
                                  fontSize=9, textColor=colors.blue, spaceAfter=16)

    # Header
    today = datetime.now().strftime("%A, %d %B %Y")
    story.append(Paragraph("🤖 Daily AI News Digest", title_style))
    story.append(Paragraph(f"Your Top 10 AI Stories — {today}", date_style))
    story.append(HRFlowable(width="100%", thickness=2,
                             color=colors.HexColor("#0f3460")))
    story.append(Spacer(1, 0.4*cm))

    # News items
    for i, article in enumerate(articles, 1):
        story.append(Paragraph(f"#{i} — {article['title']}", num_style))
        story.append(Paragraph(f"📌 {article['source']}  |  {article['date']}", src_style))
        story.append(Paragraph(article["summary"], body_style))
        story.append(Paragraph(f"🔗 {article['url']}", url_style))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                 color=colors.lightgrey))
        story.append(Spacer(1, 0.3*cm))

    # Footer
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("Generated by your AI News Digest Bot 🤖 | Powered by Claude",
                             ParagraphStyle("Footer", parent=styles["Normal"],
                                             fontSize=8, textColor=colors.grey,
                                             alignment=1)))
    doc.build(story)
    print(f"✅ PDF saved: {output_path}")
    return output_path